"""Generate LaTeX tables for the final report from the experiment manifest.

Owner: Kirill. Produces ``reports/tables/*.tex`` that ``final_report.tex`` pulls in
with ``\\input``. Tables driven by data that already exists (the dataset) are filled
with real numbers; result tables (ablation, significance) are emitted as templates
with placeholders until the experiments are run. If a results file is present at
``reports/results/metrics.json`` / ``significance.json`` those numbers are used
instead of placeholders, so re-running this script "fills in" the report.

Usage:
    python scripts/build_latex_tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "experiment_manifest.yml"
TABLES = REPO_ROOT / "reports" / "tables"
RESULTS = REPO_ROOT / "reports" / "results"

PLACEHOLDER = r"\phantom{0.000}--"

METHODS = [
    ("bm25", "BM25"),
    ("dense", "Dense"),
    ("ast", "AST candidates"),
    ("rrf", "RRF (BM25+Dense+AST)"),
    ("rrf_reranker", "RRF + Reranker"),
]
METRIC_COLS = [
    ("recall_at_1", "R@1"),
    ("recall_at_5", "R@5"),
    ("recall_at_10", "R@10"),
    ("mrr", "MRR"),
    ("map", "MAP"),
    ("ndcg_at_10", "NDCG@10"),
]


def esc(text: str) -> str:
    return str(text).replace("\\", r"\textbackslash{}").replace("_", r"\_").replace("&", r"\&")


def _load_results(name: str) -> dict:
    path = RESULTS / name
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {}


def dataset_overview(manifest: dict) -> str:
    rows = []
    for e in manifest["repositories"]:
        langs = ", ".join(e["languages"])
        rows.append(
            f"\\texttt{{{esc(e['repository_id'])}}} & {esc(langs)} & "
            f"{e['n_code_files']} & {e['n_issues']} & {e['expected_files_total']} \\\\"
        )
    d = manifest["dataset"]
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/build_latex_tables.py -- do not edit by hand.
\\begin{{tabular}}{{l l r r r}}
\\toprule
Repository & Language(s) & Files & Issues & Exp.\\ files \\\\
\\midrule
{body}
\\midrule
\\textbf{{Total ({d['n_repositories']})}} & -- & \\textbf{{{d['n_code_files']}}} & \\textbf{{{d['n_issues']}}} & \\textbf{{{d['n_expected_files']}}} \\\\
\\bottomrule
\\end{{tabular}}
"""


def language_distribution(manifest: dict) -> str:
    langs = manifest["dataset"]["languages"]
    rows = "\n".join(f"{esc(k)} & {v} \\\\" for k, v in langs.items())
    return f"""% Auto-generated by scripts/build_latex_tables.py -- do not edit by hand.
\\begin{{tabular}}{{l r}}
\\toprule
Language & Repositories \\\\
\\midrule
{rows}
\\bottomrule
\\end{{tabular}}
"""


def hyperparameter_grid(manifest: dict) -> str:
    hp = manifest["experiment"]["hyperparameters"]
    rows = "\n".join(
        f"\\texttt{{{esc(k)}}} & {esc(', '.join(map(str, v)))} \\\\" for k, v in hp.items()
    )
    return f"""% Auto-generated by scripts/build_latex_tables.py -- do not edit by hand.
\\begin{{tabular}}{{l l}}
\\toprule
Hyperparameter & Search values \\\\
\\midrule
{rows}
\\bottomrule
\\end{{tabular}}
"""


def ablation_results() -> str:
    data = _load_results("metrics.json")
    header = " & ".join(["Method"] + [c[1] for c in METRIC_COLS]) + r" \\"
    rows = []
    for key, label in METHODS:
        cells = [label]
        for mkey, _ in METRIC_COLS:
            val = data.get(key, {}).get(mkey)
            cells.append(f"{val:.3f}" if isinstance(val, (int, float)) else PLACEHOLDER)
        rows.append(" & ".join(cells) + r" \\")
    body = "\n".join(rows)
    colspec = "l" + "r" * len(METRIC_COLS)
    return f"""% Auto-generated by scripts/build_latex_tables.py.
% Fill reports/results/metrics.json to replace placeholders with real numbers.
\\begin{{tabular}}{{{colspec}}}
\\toprule
{header}
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
"""


def significance_tests() -> str:
    data = _load_results("significance.json")
    comparisons = data.get("comparisons") or [
        {"comparison": "RRF vs BM25", "metric": "NDCG@10", "delta": None, "p_value": None},
        {"comparison": "RRF vs Dense", "metric": "NDCG@10", "delta": None, "p_value": None},
        {"comparison": "RRF+Reranker vs RRF", "metric": "NDCG@10", "delta": None, "p_value": None},
    ]
    rows = []
    for c in comparisons:
        delta = c.get("delta")
        p = c.get("p_value")
        delta_s = f"{delta:+.3f}" if isinstance(delta, (int, float)) else PLACEHOLDER
        p_s = f"{p:.4f}" if isinstance(p, (int, float)) else PLACEHOLDER
        rows.append(f"{esc(c['comparison'])} & {esc(c.get('metric','--'))} & {delta_s} & {p_s} \\\\")
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/build_latex_tables.py.
% Fill reports/results/significance.json to replace placeholders.
\\begin{{tabular}}{{l l r r}}
\\toprule
Comparison & Metric & $\\Delta$ & $p$-value \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
"""


def main() -> int:
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    TABLES.mkdir(parents=True, exist_ok=True)
    outputs = {
        "dataset_overview.tex": dataset_overview(manifest),
        "language_distribution.tex": language_distribution(manifest),
        "hyperparameter_grid.tex": hyperparameter_grid(manifest),
        "ablation_results.tex": ablation_results(),
        "significance_tests.tex": significance_tests(),
    }
    for name, content in outputs.items():
        (TABLES / name).write_text(content, encoding="utf-8")
        print(f"wrote reports/tables/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
